/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedWorkspaceRouteRouteImport } from './routes/_authenticated/workspace/route'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace/index'
import { Route as AuthenticatedWorkspaceAssistantRouteImport } from './routes/_authenticated/workspace/assistant'
import { Route as AuthenticatedWorkspaceEmailRouteImport } from './routes/_authenticated/workspace/email'
import { Route as AuthenticatedWorkspaceHistoryRouteImport } from './routes/_authenticated/workspace/history'
import { Route as AuthenticatedWorkspaceMeetingsRouteImport } from './routes/_authenticated/workspace/meetings'
import { Route as AuthenticatedWorkspaceResearchRouteImport } from './routes/_authenticated/workspace/research'
import { Route as AuthenticatedWorkspaceTasksRouteImport } from './routes/_authenticated/workspace/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRouteRoute =
  AuthenticatedWorkspaceRouteRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceAssistantRoute =
  AuthenticatedWorkspaceAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceEmailRoute =
  AuthenticatedWorkspaceEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceHistoryRoute =
  AuthenticatedWorkspaceHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceMeetingsRoute =
  AuthenticatedWorkspaceMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceResearchRoute =
  AuthenticatedWorkspaceResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceTasksRoute =
  AuthenticatedWorkspaceTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/workspace/assistant': typeof AuthenticatedWorkspaceAssistantRoute
  '/workspace/email': typeof AuthenticatedWorkspaceEmailRoute
  '/workspace/history': typeof AuthenticatedWorkspaceHistoryRoute
  '/workspace/meetings': typeof AuthenticatedWorkspaceMeetingsRoute
  '/workspace/research': typeof AuthenticatedWorkspaceResearchRoute
  '/workspace/tasks': typeof AuthenticatedWorkspaceTasksRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/workspace/assistant': typeof AuthenticatedWorkspaceAssistantRoute
  '/workspace/email': typeof AuthenticatedWorkspaceEmailRoute
  '/workspace/history': typeof AuthenticatedWorkspaceHistoryRoute
  '/workspace/meetings': typeof AuthenticatedWorkspaceMeetingsRoute
  '/workspace/research': typeof AuthenticatedWorkspaceResearchRoute
  '/workspace/tasks': typeof AuthenticatedWorkspaceTasksRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/workspace/assistant': typeof AuthenticatedWorkspaceAssistantRoute
  '/_authenticated/workspace/email': typeof AuthenticatedWorkspaceEmailRoute
  '/_authenticated/workspace/history': typeof AuthenticatedWorkspaceHistoryRoute
  '/_authenticated/workspace/meetings': typeof AuthenticatedWorkspaceMeetingsRoute
  '/_authenticated/workspace/research': typeof AuthenticatedWorkspaceResearchRoute
  '/_authenticated/workspace/tasks': typeof AuthenticatedWorkspaceTasksRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/workspace'
    | '/api/chat'
    | '/workspace/assistant'
    | '/workspace/email'
    | '/workspace/history'
    | '/workspace/meetings'
    | '/workspace/research'
    | '/workspace/tasks'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/workspace/assistant'
    | '/workspace/email'
    | '/workspace/history'
    | '/workspace/meetings'
    | '/workspace/research'
    | '/workspace/tasks'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/workspace'
    | '/api/chat'
    | '/_authenticated/workspace/assistant'
    | '/_authenticated/workspace/email'
    | '/_authenticated/workspace/history'
    | '/_authenticated/workspace/meetings'
    | '/_authenticated/workspace/research'
    | '/_authenticated/workspace/tasks'
    | '/_authenticated/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/workspace/assistant': {
      id: '/_authenticated/workspace/assistant'
      path: '/assistant'
      fullPath: '/workspace/assistant'
      preLoaderRoute: typeof AuthenticatedWorkspaceAssistantRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/workspace/email': {
      id: '/_authenticated/workspace/email'
      path: '/email'
      fullPath: '/workspace/email'
      preLoaderRoute: typeof AuthenticatedWorkspaceEmailRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/workspace/history': {
      id: '/_authenticated/workspace/history'
      path: '/history'
      fullPath: '/workspace/history'
      preLoaderRoute: typeof AuthenticatedWorkspaceHistoryRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/workspace/meetings': {
      id: '/_authenticated/workspace/meetings'
      path: '/meetings'
      fullPath: '/workspace/meetings'
      preLoaderRoute: typeof AuthenticatedWorkspaceMeetingsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/workspace/research': {
      id: '/_authenticated/workspace/research'
      path: '/research'
      fullPath: '/workspace/research'
      preLoaderRoute: typeof AuthenticatedWorkspaceResearchRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/workspace/tasks': {
      id: '/_authenticated/workspace/tasks'
      path: '/tasks'
      fullPath: '/workspace/tasks'
      preLoaderRoute: typeof AuthenticatedWorkspaceTasksRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
  }
}

interface AuthenticatedWorkspaceRouteRouteChildren {
  AuthenticatedWorkspaceAssistantRoute: typeof AuthenticatedWorkspaceAssistantRoute
  AuthenticatedWorkspaceEmailRoute: typeof AuthenticatedWorkspaceEmailRoute
  AuthenticatedWorkspaceHistoryRoute: typeof AuthenticatedWorkspaceHistoryRoute
  AuthenticatedWorkspaceMeetingsRoute: typeof AuthenticatedWorkspaceMeetingsRoute
  AuthenticatedWorkspaceResearchRoute: typeof AuthenticatedWorkspaceResearchRoute
  AuthenticatedWorkspaceTasksRoute: typeof AuthenticatedWorkspaceTasksRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedWorkspaceRouteRouteChildren: AuthenticatedWorkspaceRouteRouteChildren =
  {
    AuthenticatedWorkspaceAssistantRoute: AuthenticatedWorkspaceAssistantRoute,
    AuthenticatedWorkspaceEmailRoute: AuthenticatedWorkspaceEmailRoute,
    AuthenticatedWorkspaceHistoryRoute: AuthenticatedWorkspaceHistoryRoute,
    AuthenticatedWorkspaceMeetingsRoute: AuthenticatedWorkspaceMeetingsRoute,
    AuthenticatedWorkspaceResearchRoute: AuthenticatedWorkspaceResearchRoute,
    AuthenticatedWorkspaceTasksRoute: AuthenticatedWorkspaceTasksRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  }

const AuthenticatedWorkspaceRouteRouteWithChildren =
  AuthenticatedWorkspaceRouteRoute._addFileChildren(
    AuthenticatedWorkspaceRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkspaceRouteRoute: typeof AuthenticatedWorkspaceRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkspaceRouteRoute:
    AuthenticatedWorkspaceRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
